from django.urls import path
from .views import (
    SignupView,
    LoginView,
    LogoutView,
    ForgotPasswordView,
    ResetPasswordTemplateView,
    HallListView,
    UserProfileView,
    NotificationListView,
    MarkNotificationsSeenView,
    MenuListView,
    AuthStatusView,
    FeedbackListView,
    RebateAppListView,
    MessBillView,
    MessBillPDFView,
    MyBookingListView,
    BookingListView,
    CartAddView,
    CartCheckView,
    CartCheckoutView,
    CartDeleteView,
    CustomTokenRefreshView,
    DailyRebateRefundListView,
    AdminBillingView,
    AdminBillStatusUpdateView,
    AdminSendReminderView,
    AdminExtrasDashboardView,
    AdminExtrasItemView,
    AdminFeedbackStatusUpdateView,
    AdminRebateStatusUpdateView,
    FixedChargesListView,
    AdminMenuUpdateView,
    AdminMenuDeleteView,
    AdminSendNotificationView,
    AdminStudentListView,
)

urlpatterns = [
    path('my/', AuthStatusView.as_view(), name='my'), 
    path('menu/', MenuListView.as_view(), name='menu'), 
    path('halls/', HallListView.as_view(), name='halls'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/mark-seen/', MarkNotificationsSeenView.as_view(), name='mark-notifications-seen'),
    path('feedbacks/', FeedbackListView.as_view(), name='feedbacks'),
    path('rebates/', RebateAppListView.as_view(), name='rebates'),
    path('mess-bill/', MessBillView.as_view(), name='mess-bill'),
    path('mess-bill/pdf/', MessBillPDFView.as_view(), name='mess-bill-pdf'),
    path('cart/add/', CartAddView.as_view(), name='cart-add'),
    path('cart/check/', CartCheckView.as_view(), name='cart-check'),
    path('cart/checkout/', CartCheckoutView.as_view(), name='cart-checkout'),
    path('cart/delete/', CartDeleteView.as_view(), name='cart-delete'),
    path('daily-rebate-refund/', DailyRebateRefundListView.as_view(), name='daily-rebate-refund'),
    path('admin/billing/', AdminBillingView.as_view(), name='admin-billing'),
    path('admin/billing/update-status/', AdminBillStatusUpdateView.as_view(), name='admin-billing-update-status'),
    path('admin/billing/send-reminder/', AdminSendReminderView.as_view(), name='admin-billing-send-reminder'),
    path('admin/notifications/send/', AdminSendNotificationView.as_view(), name='admin-notifications-send'),
    path('admin/notifications/students/', AdminStudentListView.as_view(), name='admin-notifications-students'),
    path('admin/feedbacks/update-status/', AdminFeedbackStatusUpdateView.as_view(), name='admin_feedback_update_status'),
    path('admin/rebates/update-status/', AdminRebateStatusUpdateView.as_view(), name='admin_rebate_update_status'),
    path('admin/menu/update/', AdminMenuUpdateView.as_view(), name='admin_menu_update'),
    path('admin/menu/delete/<int:pk>/', AdminMenuDeleteView.as_view(), name='admin_menu_delete'),
    path('fixed-charges/', FixedChargesListView.as_view(), name='fixed-charges'),
    path('bookings/', BookingListView.as_view(), name='bookings'),
    path('my-bookings/', MyBookingListView.as_view(), name='my-bookings'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('auth/refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/<uidb64>/<token>/', ResetPasswordTemplateView.as_view(), name='reset-password'),
    path('admin/extras/dashboard/', AdminExtrasDashboardView.as_view(), name='admin-extras-dashboard'),
    path('admin/extras/items/', AdminExtrasItemView.as_view(), name='admin-extras-items'),
]
