# Generated by Django 6.0.2 on 2026-03-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0005_remove_menu_day_and_time_menu_day_menu_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebateapp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
