# Generated by Django 6.0.2 on 2026-03-21 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0006_rebateapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='month',
            field=models.CharField(default='Error', max_length=20),
        ),
        migrations.CreateModel(
            name='FixedCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_charges', to='Backend_App.hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_charges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
