# Generated by Django 6.0.2 on 2026-03-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0007_item_month_fixedcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRebateRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='Error', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
