# Generated by Django 6.0.2 on 2026-03-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0008_dailyrebaterefund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessBill',
        ),
    ]
