# Generated by Django 6.0.2 on 2026-03-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0010_billverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='expires_at',
        ),
    ]
