# Generated by Django 6.0.2 on 2026-03-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0011_remove_cart_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooking',
            name='status',
            field=models.CharField(choices=[('confirmed-not-scanned', 'Confirmed-Not-Scanned'), ('confirmed-scanned', 'Confirmed-Scanned'), ('cancelled', 'Cancelled')], default='confirmed', max_length=50),
        ),
    ]
