# Generated by Django 6.0.2 on 2026-03-27 13:17

import Backend_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0016_remove_mybooking_qr_code_id_remove_qrdatabase_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrebaterefund',
            name='month',
            field=models.CharField(default=Backend_App.models.current_month_name, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='month',
            field=models.CharField(default=Backend_App.models.current_month_name, max_length=20),
        ),
    ]
