# Generated by Django 6.0.2 on 2026-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_App', '0017_default_month_current'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('available_count__gte', 0)), name='booking_available_count_non_negative'),
        ),
    ]
